spring.application.name=wiretap

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:postgresql://localhost:5432/wiretap
spring.datasource.username=wiretap_user
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.file.name=logs/app.log
logging.level.root=INFO

spring.security.user.name=user
spring.security.user.password=pass123

jwt.secret="gdklelkfkfjnkmkrekknkenkkrkfejbhbheuieieiowwjooeeihu"
